// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJQMQ6VHPOiP1bsDfURnY-OKua1t_u6H8',
    appId: '1:418019899255:android:0cdec821f1387fa1e19372',
    messagingSenderId: '418019899255',
    projectId: 'maluian-pets',
    storageBucket: 'maluian-pets.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3aFR2ciGvUprDLAu5ErTmKGK1990gWIs',
    appId: '1:418019899255:ios:3fb1ca27ad7c0038e19372',
    messagingSenderId: '418019899255',
    projectId: 'maluian-pets',
    storageBucket: 'maluian-pets.firebasestorage.app',
    iosClientId: '418019899255-52upnt2am1bsf2dcoucaa4vq4opfj8g7.apps.googleusercontent.com',
    iosBundleId: 'com.example.proyecto',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_j_VYj563OJyGD2ZTO9iF7xlaJau7WBo',
    appId: '1:418019899255:web:4f62fa587bbc380de19372',
    messagingSenderId: '418019899255',
    projectId: 'maluian-pets',
    authDomain: 'maluian-pets.firebaseapp.com',
    storageBucket: 'maluian-pets.firebasestorage.app',
    measurementId: 'G-73GS6SENP9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3aFR2ciGvUprDLAu5ErTmKGK1990gWIs',
    appId: '1:418019899255:ios:3fb1ca27ad7c0038e19372',
    messagingSenderId: '418019899255',
    projectId: 'maluian-pets',
    storageBucket: 'maluian-pets.firebasestorage.app',
    iosClientId: '418019899255-52upnt2am1bsf2dcoucaa4vq4opfj8g7.apps.googleusercontent.com',
    iosBundleId: 'com.example.proyecto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_j_VYj563OJyGD2ZTO9iF7xlaJau7WBo',
    appId: '1:418019899255:web:3dadd339698768c1e19372',
    messagingSenderId: '418019899255',
    projectId: 'maluian-pets',
    authDomain: 'maluian-pets.firebaseapp.com',
    storageBucket: 'maluian-pets.firebasestorage.app',
    measurementId: 'G-SJW08D4VSE',
  );

}